name       : python-pure-eval
version    : 0.2.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pure_eval/pure_eval-0.2.2.tar.gz : 2b45320af6dfaa1750f543d714b6d1c520a1688dec6fd24d339063ce0aaa9ac3
homepage   : https://github.com/alexmojaki/pure_eval
license    : MIT
component  : programming.python
summary    : Safely evaluate AST nodes without side effects
description: |
    This is a Python package that lets you safely evaluate certain AST nodes without triggering arbitrary code that may have unwanted side effects.
builddeps  :
    - python-build
    - python-installer
    - python-pytest         # check
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
